/**
 *
 * $Id$
 */
package ClassDiagram.validation;

import ClassDiagram.Classifier;

/**
 * A sample validator interface for {@link ClassDiagram.Attribute}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface AttributeValidator {
	boolean validate();

	boolean validateMultiValued(Boolean value);

	boolean validateMultiValued(Object value);
	boolean validateType(Classifier value);
	boolean validateOwner(ClassDiagram.Class value);
}
