/**
 *
 * $Id$
 */
package fr.inria.atlanmod.mogwai.gremlin.validation;

import fr.inria.atlanmod.mogwai.gremlin.TraversalElement;

/**
 * A sample validator interface for {@link fr.inria.atlanmod.mogwai.gremlin.TraversalElement}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface TraversalElementValidator {
	boolean validate();

	boolean validateNextElement(TraversalElement value);
	boolean validatePreviousElement(TraversalElement value);
}
